#include "RecoLocalTracker/SiStripClusterizer/interface/SiStripClusterizerConditionsHost.h"
#include "RecoLocalTracker/SiStripClusterizer/interface/SiStripClusterizerConditionsHostObject.h"
#include "FWCore/Utilities/interface/typelookup.h"

TYPELOOKUP_DATA_REG(sistrip::SiStripClusterizerConditionsDetToFedsHost);
TYPELOOKUP_DATA_REG(sistrip::SiStripClusterizerConditionsDataHost);

TYPELOOKUP_DATA_REG(sistrip::SiStripClusterizerConditionsDetToFedsHostObject);
TYPELOOKUP_DATA_REG(sistrip::SiStripClusterizerConditionsDataHostObject);
